# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopping_assistant.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18shopping_assistant.proto\"$\n\x0f\x46ileNameRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"(\n\x18ShoppingListItemResponse\x12\x0c\n\x04item\x18\x01 \x01(\t2P\n\x11ShoppingAssistant\x12;\n\x0cPostFileName\x12\x10.FileNameRequest\x1a\x19.ShoppingListItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shopping_assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILENAMEREQUEST']._serialized_start=28
  _globals['_FILENAMEREQUEST']._serialized_end=64
  _globals['_SHOPPINGLISTITEMRESPONSE']._serialized_start=66
  _globals['_SHOPPINGLISTITEMRESPONSE']._serialized_end=106
  _globals['_SHOPPINGASSISTANT']._serialized_start=108
  _globals['_SHOPPINGASSISTANT']._serialized_end=188
# @@protoc_insertion_point(module_scope)
